/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.interfaces


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
interface IFlywaySchemaHistory : Serializable {
    var installedRank: Int?
    var version: String?
    var description: String?
    var type: String?
    var script: String?
    var checksum: Int?
    var installedBy: String?
    var installedOn: LocalDateTime?
    var executionTime: Int?
    var success: Boolean?

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IFlywaySchemaHistory
     */
    fun from(from: IFlywaySchemaHistory)

    /**
     * Copy data into another generated Record/POJO implementing the common interface IFlywaySchemaHistory
     */
    fun <E : IFlywaySchemaHistory> into(into: E): E
}
