/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.interfaces


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
interface ILogs : Serializable {
    var id: Int?
    var sessionId: String?
    var kind: String?
    var ipAddress: String?
    var input: String?
    var output: String?
    var error: String?
    var createdAt: LocalDateTime?

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ILogs
     */
    fun from(from: ILogs)

    /**
     * Copy data into another generated Record/POJO implementing the common interface ILogs
     */
    fun <E : ILogs> into(into: E): E
}
