/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.keys


import io.github.novemdecillion.adapter.jooq.tables.FlywaySchemaHistoryTable
import io.github.novemdecillion.adapter.jooq.tables.LogsTable
import io.github.novemdecillion.adapter.jooq.tables.records.FlywaySchemaHistoryRecord
import io.github.novemdecillion.adapter.jooq.tables.records.LogsRecord

import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val FLYWAY_SCHEMA_HISTORY_PK: UniqueKey<FlywaySchemaHistoryRecord> = Internal.createUniqueKey(FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), arrayOf(FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK), true)
val LOGS_PKEY: UniqueKey<LogsRecord> = Internal.createUniqueKey(LogsTable.LOGS, DSL.name("logs_pkey"), arrayOf(LogsTable.LOGS.ID), true)
