/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.references


import io.github.novemdecillion.adapter.jooq.tables.FlywaySchemaHistoryTable
import io.github.novemdecillion.adapter.jooq.tables.LogsTable



/**
 * The table <code>flyway_schema_history</code>.
 */
val FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY

/**
 * The table <code>logs</code>.
 */
val LOGS = LogsTable.LOGS
