/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq


import io.github.novemdecillion.adapter.jooq.sequences.LOGS_ID_SEQ
import io.github.novemdecillion.adapter.jooq.tables.FlywaySchemaHistoryTable
import io.github.novemdecillion.adapter.jooq.tables.LogsTable

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Sequence
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DefaultSchema : SchemaImpl("", DefaultCatalog.DEFAULT_CATALOG) {
    companion object {

        /**
         * The reference instance of <code>DEFAULT_SCHEMA</code>
         */
        val DEFAULT_SCHEMA = DefaultSchema()
    }

    /**
     * The table <code>flyway_schema_history</code>.
     */
    val FLYWAY_SCHEMA_HISTORY get() = FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY

    /**
     * The table <code>logs</code>.
     */
    val LOGS get() = LogsTable.LOGS

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getSequences(): List<Sequence<*>> = listOf(
        LOGS_ID_SEQ
    )

    override fun getTables(): List<Table<*>> = listOf(
        FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY,
        LogsTable.LOGS
    )
}
