/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.sequences


import io.github.novemdecillion.adapter.jooq.DefaultSchema

import org.jooq.Sequence
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType



/**
 * The sequence <code>logs_id_seq</code>
 */
val LOGS_ID_SEQ: Sequence<Int> = Internal.createSequence("logs_id_seq", DefaultSchema.DEFAULT_SCHEMA, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null)
