/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.indexes


import io.github.novemdecillion.adapter.jooq.tables.FlywaySchemaHistoryTable

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val FLYWAY_SCHEMA_HISTORY_S_IDX: Index = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY, arrayOf(FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY.SUCCESS), false)
