/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.pojos


import io.github.novemdecillion.adapter.jooq.tables.interfaces.IFlywaySchemaHistory

import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class FlywaySchemaHistoryEntity(
    override var installedRank: Int? = null, 
    override var version: String? = null, 
    override var description: String? = null, 
    override var type: String? = null, 
    override var script: String? = null, 
    override var checksum: Int? = null, 
    override var installedBy: String? = null, 
    override var installedOn: LocalDateTime? = null, 
    override var executionTime: Int? = null, 
    override var success: Boolean? = null
): IFlywaySchemaHistory {


    override fun toString(): String {
        val sb = StringBuilder("FlywaySchemaHistoryEntity (")

        sb.append(installedRank)
        sb.append(", ").append(version)
        sb.append(", ").append(description)
        sb.append(", ").append(type)
        sb.append(", ").append(script)
        sb.append(", ").append(checksum)
        sb.append(", ").append(installedBy)
        sb.append(", ").append(installedOn)
        sb.append(", ").append(executionTime)
        sb.append(", ").append(success)

        sb.append(")")
        return sb.toString()
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    override fun from(from: IFlywaySchemaHistory) {
        installedRank = from.installedRank
        version = from.version
        description = from.description
        type = from.type
        script = from.script
        checksum = from.checksum
        installedBy = from.installedBy
        installedOn = from.installedOn
        executionTime = from.executionTime
        success = from.success
    }

    override fun <E : IFlywaySchemaHistory> into(into: E): E {
        into.from(this)
        return into
    }
}
