/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.adapter.jooq.tables.pojos


import io.github.novemdecillion.adapter.jooq.tables.interfaces.ILogs

import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class LogsEntity(
    override var id: Int? = null, 
    override var sessionId: String? = null, 
    override var kind: String? = null, 
    override var ipAddress: String? = null, 
    override var input: String? = null, 
    override var output: String? = null, 
    override var error: String? = null, 
    override var createdAt: LocalDateTime? = null
): ILogs {


    override fun toString(): String {
        val sb = StringBuilder("LogsEntity (")

        sb.append(id)
        sb.append(", ").append(sessionId)
        sb.append(", ").append(kind)
        sb.append(", ").append(ipAddress)
        sb.append(", ").append(input)
        sb.append(", ").append(output)
        sb.append(", ").append(error)
        sb.append(", ").append(createdAt)

        sb.append(")")
        return sb.toString()
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    override fun from(from: ILogs) {
        id = from.id
        sessionId = from.sessionId
        kind = from.kind
        ipAddress = from.ipAddress
        input = from.input
        output = from.output
        error = from.error
        createdAt = from.createdAt
    }

    override fun <E : ILogs> into(into: E): E {
        into.from(this)
        return into
    }
}
